// Background worker: the only part that talks to Jev (the Gmail page can't call other sites).
// Receives one email's text, returns { action, topic, urgency, review, source }.
importScripts('taxonomy.js');
const T = self.JEV_TAXONOMY;

const JEV_URL = 'https://api.typesafe.ai/v1/systemone';
const JEV_MODEL = 'jev-latest';
const LOW_CONF_GAP = 0.15;

function questions(t) {
  const crit = list => Object.fromEntries(list.map(x => [x.key, x.desc || x.label]));
  return {
    action: {
      type: 'choice',
      instructions: 'What should the recipient DO with this email? Judge from sender, recipients, subject and body together.',
      criteria: crit(t.actions),
    },
    topic: { type: 'choice', instructions: 'What is this email mainly about?', criteria: crit(t.topics) },
    urgency: {
      type: 'score',
      instructions: 'How soon does the recipient need to deal with this?',
      criteria: [
        'Never, or no time pressure',
        'Sometime this week',
        'Within a couple of days',
        'Today',
        'Right now: someone is blocked, a deadline is within hours, or an account may be compromised',
      ],
    },
    is_personal: {
      type: 'noul',
      instructions: 'Was this written by a human specifically to the recipient, rather than sent to a list or generated by a system?',
    },
  };
}

async function classify(text, fromEmail) {
  const t = await T.load();
  const rule = T.ruleFor(t, fromEmail);

  // Known bulk sender with a fixed action: no need to ask Jev.
  if (rule && rule.action && T.byKey(t.actions, rule.action) && T.byKey(t.topics, rule.topic)) {
    return { action: rule.action, topic: rule.topic, urgency: 1, review: false, mustSee: !!rule.mustSee, source: 'rule' };
  }

  const { jevKey } = await chrome.storage.local.get('jevKey');
  if (!jevKey) throw new Error('No Jev API key yet. Click the extension icon → Options and paste it.');
  const res = await fetch(JEV_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', Authorization: 'Bearer ' + jevKey },
    body: JSON.stringify({ model: JEV_MODEL, state: text, questions: questions(t) }),
  });
  if (res.status === 429 || res.status === 529) return { rateLimited: true };
  if (!res.ok) throw new Error('Jev HTTP ' + res.status + ': ' + (await res.text()).slice(0, 160));
  const a = (await res.json()).answers;

  const probs = Object.values(a.action.probabilities || {}).sort((x, y) => y - x);
  const fallbackAction = T.byKey(t.actions, 'low') ? 'low' : t.actions[t.actions.length - 1].key;
  let action = T.byKey(t.actions, a.action.choice) ? a.action.choice : fallbackAction;
  let topic = T.byKey(t.topics, a.topic.choice) ? a.topic.choice : t.topics[t.topics.length - 1].key;
  if (rule && T.byKey(t.topics, rule.topic)) topic = rule.topic;
  // Jevmail maps Jev's weighted score to 1..5 with round(score)+1.
  const urgency = Math.min(5, Math.max(1, Math.round(Number(a.urgency.score)) + 1));
  if (action === 'low' && T.byKey(t.actions, 'reply') && a.is_personal && a.is_personal.noul > 0.8) action = 'reply';
  const personal = a.is_personal ? Number(a.is_personal.noul) : 0;
  const ignored = (t.ignoreActions || []).includes(action);
  const mustSee = !!(rule && rule.mustSee) ||
    (!ignored && (action === 'reply' || action === 'action' || urgency >= 4 || personal > 0.8));
  return { action, topic, urgency, mustSee, review: probs.length > 1 && probs[0] - probs[1] < LOW_CONF_GAP, source: 'jev' };
}

chrome.runtime.onMessage.addListener((msg, _sender, reply) => {
  if (msg.cmd === 'classify') {
    classify(msg.text, msg.fromEmail).then(reply, e => reply({ error: String(e.message || e) }));
    return true;
  }
  if (msg.cmd === 'openOptions') { chrome.runtime.openOptionsPage(); reply({ ok: true }); }
});
